name: Lawyer
version: '${project.version}'
main: com.pinecarp.lawyer.Main
api-version: 1.17
authors: [ pinecarp ]
description: A Minecraft Plugin
commands:
  lawyer:
    description: Give a Pickaxe
    command: /<command>
